from django.db.models import TextChoices

DATE_FORMAT_LONG = "%B %d, %Y, %H:%M"
DATE_FORMAT_SHORT = "%B %d %Y"
DATE_FORMAT_NUMERIC = "%Y-%m-%d"
DATE_FORMAT_NUMERIC_SLASHES = "%d/%m/%Y"


class EngagementType(TextChoices):
    TYPE_LEGACY = "Legacy", "Legacy"
    TYPE_EMAIL_WEBSITE = "email_website", "Email or website"
    TYPE_FACE_TO_FACE = "face_to_face", "Face to face"
    TYPE_LETTER = "letter", "Letter"
    TYPE_NON_CONTACT_RESEARCH = "non_contact_research", "Non contact research"
    TYPE_SOCIAL_MEDIA = "social_media", "Social media"
    TYPE_TELEPHONE = "telephone", "Telephone"
    TYPE_VIDEO_TELECONF = "video_teleconf", "Video or teleconference"


ENGAGEMENT_TYPE_COLOUR_MAPPING = {
    EngagementType.TYPE_LEGACY: "grey",
    EngagementType.TYPE_EMAIL_WEBSITE: "light-blue",
    EngagementType.TYPE_FACE_TO_FACE: "pink",
    EngagementType.TYPE_LETTER: "yellow",
    EngagementType.TYPE_NON_CONTACT_RESEARCH: "grey",
    EngagementType.TYPE_SOCIAL_MEDIA: "purple",
    EngagementType.TYPE_TELEPHONE: "green",
    EngagementType.TYPE_VIDEO_TELECONF: "orange",
}

# react only uses the human readable value. the db wants the internal value of the engagement type
# annoyingly this isn't a built in function in django's TextChoices enum class
ENGAGEMENT_TYPE_MAP = {
    label: value for value, label in zip(EngagementType.values, EngagementType.labels)
}

# users should not be able to select the "Legacy" type
ENGAGEMENT_TYPE_OPTIONS = [
    label
    for value, label in EngagementType.choices
    if value != EngagementType.TYPE_LEGACY
]


# DBT's official list of countries and territories
COUNTRIES_AND_TERRITORIES = (
    ("AE-AZ", "Abu Dhabi"),
    ("AF", "Afghanistan"),
    ("AE-AJ", "Ajman"),
    ("XQZ", "Akrotiri"),
    ("AX", "Åland Islands"),
    ("AL", "Albania"),
    ("DZ", "Algeria"),
    ("AS", "American Samoa"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AI", "Anguilla"),
    ("AG", "Antigua and Barbuda"),
    ("AR", "Argentina"),
    ("AM", "Armenia"),
    ("AW", "Aruba"),
    ("SH-AC", "Ascension"),
    ("AU", "Australia"),
    ("AT", "Austria"),
    ("AZ", "Azerbaijan"),
    ("BH", "Bahrain"),
    ("UM-81", "Baker Island"),
    ("BD", "Bangladesh"),
    ("BB", "Barbados"),
    ("BY", "Belarus"),
    ("BE", "Belgium"),
    ("BZ", "Belize"),
    ("BJ", "Benin"),
    ("BM", "Bermuda"),
    ("BT", "Bhutan"),
    ("BO", "Bolivia"),
    ("BQ-BO", "Bonaire"),
    ("BA", "Bosnia and Herzegovina"),
    ("BW", "Botswana"),
    ("BR", "Brazil"),
    ("IO", "British Indian Ocean Territory"),
    ("VG", "British Virgin Islands"),
    ("BN", "Brunei"),
    ("BG", "Bulgaria"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("KH", "Cambodia"),
    ("CM", "Cameroon"),
    ("CA", "Canada"),
    ("CV", "Cape Verde"),
    ("KY", "Cayman Islands"),
    ("CF", "Central African Republic"),
    ("ES-CE", "Ceuta"),
    ("TD", "Chad"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CX", "Christmas Island"),
    ("CC", "Cocos (Keeling) Islands"),
    ("CO", "Colombia"),
    ("KM", "Comoros"),
    ("CG", "Congo"),
    ("CD", "Congo (Democratic Republic)"),
    ("CK", "Cook Islands"),
    ("CR", "Costa Rica"),
    ("HR", "Croatia"),
    ("CU", "Cuba"),
    ("CW", "Curaçao"),
    ("CY", "Cyprus"),
    ("CZ", "Czechia"),
    ("DK", "Denmark"),
    ("XXD", "Dhekelia"),
    ("DJ", "Djibouti"),
    ("DM", "Dominica"),
    ("DO", "Dominican Republic"),
    ("AE-DU", "Dubai"),
    ("TL", "East Timor"),
    ("EC", "Ecuador"),
    ("EG", "Egypt"),
    ("SV", "El Salvador"),
    ("GQ", "Equatorial Guinea"),
    ("ER", "Eritrea"),
    ("EE", "Estonia"),
    ("SZ", "Eswatini"),
    ("ET", "Ethiopia"),
    ("FK", "Falkland Islands"),
    ("FO", "Faroe Islands"),
    ("FM", "Federated States of Micronesia’"),
    ("FJ", "Fiji"),
    ("FI", "Finland"),
    ("FR", "France"),
    ("GF", "French Guiana"),
    ("PF", "French Polynesia"),
    ("AE-FU", "Fujairah"),
    ("GA", "Gabon"),
    ("GE", "Georgia"),
    ("DE", "Germany"),
    ("GH", "Ghana"),
    ("GI", "Gibraltar"),
    ("GR", "Greece"),
    ("GL", "Greenland"),
    ("GD", "Grenada"),
    ("GP", "Guadeloupe"),
    ("GU", "Guam"),
    ("GT", "Guatemala"),
    ("GG", "Guernsey"),
    ("GN", "Guinea"),
    ("GW", "Guinea-Bissau"),
    ("GY", "Guyana"),
    ("HT", "Haiti"),
    ("HN", "Honduras"),
    ("HK", "Hong Kong"),
    ("UM-84", "Howland Island"),
    ("HU", "Hungary"),
    ("IS", "Iceland"),
    ("IN", "India"),
    ("ID", "Indonesia"),
    ("IR", "Iran"),
    ("IQ", "Iraq"),
    ("IE", "Ireland"),
    ("IM", "Isle of Man"),
    ("IL", "Israel"),
    ("IT", "Italy"),
    ("CI", "Ivory Coast"),
    ("JM", "Jamaica"),
    ("JP", "Japan"),
    ("UM-86", "Jarvis Island"),
    ("JE", "Jersey"),
    ("UM-67", "Johnston Atoll"),
    ("JO", "Jordan"),
    ("KZ", "Kazakhstan"),
    ("KE", "Kenya"),
    ("UM-89", "Kingman Reef"),
    ("KI", "Kiribati"),
    ("XK", "Kosovo"),
    ("KW", "Kuwait"),
    ("KG", "Kyrgyzstan"),
    ("LA", "Laos"),
    ("LV", "Latvia"),
    ("LB", "Lebanon"),
    ("LS", "Lesotho"),
    ("LR", "Liberia"),
    ("LY", "Libya"),
    ("LI", "Liechtenstein"),
    ("LT", "Lithuania"),
    ("LU", "Luxembourg"),
    ("MO", "Macao"),
    ("MG", "Madagascar"),
    ("MW", "Malawi"),
    ("MY", "Malaysia"),
    ("MV", "Maldives"),
    ("ML", "Mali"),
    ("MT", "Malta"),
    ("MH", "Marshall Islands"),
    ("MQ", "Martinique"),
    ("MR", "Mauritania"),
    ("MU", "Mauritius"),
    ("YT", "Mayotte"),
    ("ES-ML", "Melilla"),
    ("MX", "Mexico"),
    ("UM-71", "Midway Islands"),
    ("MD", "Moldova"),
    ("MC", "Monaco"),
    ("MN", "Mongolia"),
    ("ME", "Montenegro"),
    ("MS", "Montserrat"),
    ("MA", "Morocco"),
    ("MZ", "Mozambique"),
    ("MM", "Myanmar (Burma)"),
    ("NA", "Namibia"),
    ("NR", "Nauru"),
    ("UM-76", "Navassa Island"),
    ("NP", "Nepal"),
    ("NL", "Netherlands"),
    ("NC", "New Caledonia"),
    ("NZ", "New Zealand"),
    ("NI", "Nicaragua"),
    ("NE", "Niger"),
    ("NG", "Nigeria"),
    ("NU", "Niue"),
    ("NF", "Norfolk Island"),
    ("MP", "Northern Mariana Islands"),
    ("KP", "North Korea"),
    ("MK", "North Macedonia"),
    ("NO", "Norway"),
    ("PS", "Occupied Palestinian Territories"),
    ("OM", "Oman"),
    ("PK", "Pakistan"),
    ("PW", "Palau"),
    ("UM-95", "Palmyra Atoll"),
    ("PA", "Panama"),
    ("PG", "Papua New Guinea"),
    ("PY", "Paraguay"),
    ("PE", "Peru"),
    ("PH", "Philippines"),
    ("PN", "Pitcairn, Henderson, Ducie and Oeno Islands"),
    ("PL", "Poland"),
    ("PT", "Portugal"),
    ("PR", "Puerto Rico"),
    ("QA", "Qatar"),
    ("AE-RK", "Ras al-Khaimah"),
    ("RE", "Réunion"),
    ("RO", "Romania"),
    ("RU", "Russia"),
    ("RW", "Rwanda"),
    ("BQ-SA", "Saba"),
    ("BL", "Saint Barthélemy"),
    ("SH-HL", "Saint Helena"),
    ("MF", "Saint-Martin (French part)"),
    ("PM", "Saint Pierre and Miquelon"),
    ("WS", "Samoa"),
    ("SM", "San Marino"),
    ("ST", "Sao Tome and Principe"),
    ("SA", "Saudi Arabia"),
    ("SN", "Senegal"),
    ("RS", "Serbia"),
    ("SC", "Seychelles"),
    ("AE-SH", "Sharjah"),
    ("SL", "Sierra Leone"),
    ("SG", "Singapore"),
    ("BQ-SE", "Sint Eustatius"),
    ("SX", "Sint Maarten (Dutch part)"),
    ("SK", "Slovakia"),
    ("SI", "Slovenia"),
    ("SB", "Solomon Islands"),
    ("SO", "Somalia"),
    ("ZA", "South Africa"),
    ("GS", "South Georgia and South Sandwich Islands"),
    ("KR", "South Korea"),
    ("SS", "South Sudan"),
    ("ES", "Spain"),
    ("LK", "Sri Lanka"),
    ("KN", "St Kitts and Nevis"),
    ("LC", "St Lucia"),
    ("VC", "St Vincent"),
    ("SD", "Sudan"),
    ("SR", "Suriname"),
    ("SJ", "Svalbard and Jan Mayen"),
    ("SE", "Sweden"),
    ("CH", "Switzerland"),
    ("SY", "Syria"),
    ("TW", "Taiwan"),
    ("TJ", "Tajikistan"),
    ("TZ", "Tanzania"),
    ("TH", "Thailand"),
    ("BS", "The Bahamas"),
    ("GM", "The Gambia"),
    ("TG", "Togo"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TT", "Trinidad and Tobago"),
    ("SH-TA", "Tristan da Cunha"),
    ("TN", "Tunisia"),
    ("TR", "Turkey"),
    ("TM", "Turkmenistan"),
    ("TC", "Turks and Caicos Islands"),
    ("TV", "Tuvalu"),
    ("UG", "Uganda"),
    ("UA", "Ukraine"),
    ("AE-UQ", "Umm al-Quwain"),
    ("AE", "United Arab Emirates"),
    ("GB", "United Kingdom"),
    ("US", "United States"),
    ("VI", "United States Virgin Islands"),
    ("UY", "Uruguay"),
    ("UZ", "Uzbekistan"),
    ("VU", "Vanuatu"),
    ("VA", "Vatican City"),
    ("VE", "Venezuela"),
    ("VN", "Vietnam"),
    ("UM-79", "Wake Island"),
    ("WF", "Wallis and Futuna"),
    ("EH", "Western Sahara"),
    ("YE", "Yemen"),
    ("ZM", "Zambia"),
    ("ZW", "Zimbabwe"),
)

SECTORS = (
    ("SL0001", "Advanced engineering"),
    ("SL0011", "Aerospace"),
    ("SL0022", "Agriculture, horticulture, fisheries and pets"),
    ("SL0049", "Airports"),
    ("SL0050", "Automotive"),
    ("SL0071", "Chemicals"),
    ("SL0077", "Construction"),
    ("SL0078", "Consumer and retail"),
    ("SL0102", "Creative industries"),
    ("SL0139", "Defence"),
    ("SL0140", "Education and training"),
    ("SL0169", "Energy"),
    ("SL0187", "Environment"),
    ("SL0194", "Financial and professional services"),
    ("SL0221", "Food and drink"),
    ("SL0236", "Healthcare services"),
    ("SL0432", "Logistics"),
    ("SL0245", "Maritime"),
    ("SL0274", "Medical devices and equipment"),
    ("SL0279", "Mining"),
    ("SL0280", "Pharmaceuticals and biotechnology"),
    ("SL0286", "Railways"),
    ("SL0287", "Security"),
    ("SL0289", "Space"),
    ("SL0305", "Sports economy"),
    ("SL0312", "Technology and smart cities"),
    ("SL0337", "Water"),
)
