name: scl

services:
  postgres:
    image: postgres:16
    networks:
      - scl
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scl
    volumes:
      - scl:/var/lib/postgresql/data
  web-dev:
    restart: always
    networks:
      - scl
    build:
      context: .
      target: dev
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      PGHOST: postgres
      PGDATABASE: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password
    volumes:
       - ./scl/core/templates:/app/scl/core/templates
       - ./scl/core/static:/app/scl/core/static
    profiles: ['']
  web-prod:
    build:
      context: .
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    environment:
      PGHOST: postgres
      PGDATABASE: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: password
    profiles: ['prod']

networks:
  scl:
    name: scl

volumes:
    scl:
