name: scl

services:
  postgres:
    image: postgres:16
    networks:
      - scl-network
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scl
    ports:
      - "5432:5432"
    volumes:
      - scldata:/var/lib/postgresql/data
  web-dev:
    restart: always
    networks:
      - scl-network
    build:
      context: .
      target: dev
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
    volumes:
       - ./scl/core/templates:/app/scl/core/templates
       - ./scl/core/static:/app/scl/core/static
    profiles: ['']
  web-prod:
    build:
      context: .
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    profiles: ['prod']

networks:
  scl-network:
    name: scl-network
    driver: bridge

volumes:
    scldata:
