services:
  web-dev:
    restart: always
    build:
      context: .
      target: dev
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
    volumes:
       - ./scl/core/templates:/app/scl/core/templates
       - ./scl/core/static:/app/scl/core/static
    profiles: ['']
  web-prod:
    build:
      context: .
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    profiles: ['prod']
