name: scl-e2e

services:
  postgres:
    volumes:
      - scl-e2e:/var/lib/postgresql/data
  web-dev:
    build:
      context: .
      target: e2e
    env_file: .env
    volumes:
      - ./start-e2e.sh:/app/start-e2e.sh
      - ./scl/core/fixtures:/app/scl/core/fixtures
    profiles: ["e2e"]

volumes:
    scl-e2e:
