name: scl

services:
  postgres:
    image: postgres:16
    networks:
      - scl
    environment:
      - POSTGRES_DB=scl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - scl:/var/lib/postgresql/data
    ports:
      - 5432:5432
  sso:
    build: https://github.com/uktrade/mock-sso.git
    networks:
      - scl
    ports:
      - "8001:8001"
    environment:
      MOCK_SSO_PORT: 8001
      MOCK_SSO_USER_EMAIL: local.user@businessandtrade.gov.uk
      MOCK_SSO_TOKEN: local.token
      MOCK_SSO_CODE: local.code
  web-dev:
    restart: always
    networks:
      - scl
    depends_on:
      - postgres
      - sso
    build:
      context: .
      target: dev
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      PGDATABASE: scl
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: postgres
      PGPORT: 5432
      OAUTHLIB_INSECURE_TRANSPORT: 1
      AUTHBROKER_URL: 'http://localhost:8001/'
      AUTHBROKER_INTERNAL_URL: 'http://sso:8001/'
      AUTHBROKER_CLIENT_ID: 'any'
      AUTHBROKER_CLIENT_SECRET: 'any'
      IP_FILTER_ALLOWED_NETWORKS: '{"all":["0.0.0.0/0"]}'
    env_file:
      - .env
    volumes:
       - ./scl/core/templates:/app/scl/core/templates
       - ./scl/core/migrations:/app/scl/core/migrations
       - ./scl/core/static:/app/scl/core/static
       - ./scl/core/views:/app/scl/core/views
       - ./scl/core/views/html.py:/app/scl/core/views/html.py
       - ./scl/core/models.py:/app/scl/core/models.py
       - ./scl/core/forms.py:/app/scl/core/forms.py
       - ~/.aws:/home/scl/.aws
    profiles: ['']
  web-prod:
    networks:
      - scl
    depends_on:
      - postgres
      - sso
    build:
      context: .
      args:
        - GIT_COMMIT=to-be-set-by-codebuild
    ports:
      - "8000:8000"
    environment:
      PGDATABASE: scl
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: postgres
      PGPORT: 5432
      OAUTHLIB_INSECURE_TRANSPORT: 1
      AUTHBROKER_URL: 'http://localhost:8001/'
      AUTHBROKER_INTERNAL_URL: 'http://sso:8001/'
      AUTHBROKER_CLIENT_ID: 'any'
      AUTHBROKER_CLIENT_SECRET: 'any'
      IP_FILTER_ALLOWED_NETWORKS: '{"all":["0.0.0.0/0"]}'
    env_file:
      - .env
    volumes:
      - ~/.aws:/home/scl/.aws
    profiles: ['prod']

networks:
  scl:
    name: scl

volumes:
    scl:
