# Generated by Django 5.1.8 on 2025-05-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypeople',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
