# Generated by Django 5.1.6 on 2025-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='issues',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='priorities',
            field=models.TextField(null=True),
        ),
    ]
