# Generated by Django 5.1.6 on 2025-03-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_issues_company_priorities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
