# Generated by Django 5.1.9 on 2025-05-19 15:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_keypeople_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='details',
            new_name='actions',
        ),
        migrations.AddField(
            model_name='engagement',
            name='agenda',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='civil_servants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='engagement',
            name='company_representatives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='engagement',
            name='engagement_type',
            field=models.CharField(choices=[('legacy', 'legacy'), ('email_website', 'Email/Website'), ('face_to_face', 'Face to Face'), ('find_exporters', 'Find Exporters'), ('letter', 'Letter'), ('non_contact_research', 'Non contact research'), ('social_media', 'Social Media'), ('telephone', 'Telephone'), ('video_Teleconf', 'Video/Teleconf')], default='legacy', max_length=128),
        ),
        migrations.AddField(
            model_name='engagement',
            name='ministers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='engagement',
            name='outcomes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
