# Generated by Django 5.1.6 on 2025-03-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='duns_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
