# Generated by Django 5.1.6 on 2025-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_duns_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='duns_number',
            field=models.CharField(max_length=9, verbose_name='DUNS number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='issues',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='key_facts',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='priorities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
