# Generated by Django 5.1.9 on 2025-05-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_engagement_engagement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='engagement_type',
            field=models.CharField(choices=[('legacy', 'legacy'), ('email_website', 'Email/Website'), ('face_to_face', 'Face to Face'), ('letter', 'Letter'), ('non_contact_research', 'Non contact research'), ('social_media', 'Social Media'), ('telephone', 'Telephone'), ('video_Teleconf', 'Video/Teleconf')], max_length=128),
        ),
    ]
