# Generated by Django 5.1.6 on 2025-03-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_duns_number_alter_company_issues_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='issues',
            new_name='company_priorities',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='key_facts',
            new_name='hmg_priorities',
        ),
        migrations.RemoveField(
            model_name='company',
            name='priorities',
        ),
    ]
