# Generated by Django 5.1.9 on 2025-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_engagement_engagement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='engagement_type',
            field=models.CharField(choices=[('Legacy', 'Legacy'), ('email_website', 'Email or website'), ('face_to_face', 'Face to face'), ('letter', 'Letter'), ('non_contact_research', 'Non contact research'), ('social_media', 'Social media'), ('telephone', 'Telephone'), ('video_teleconf', 'Video or teleconference')], max_length=128),
        ),
    ]
