# Generated by Django 5.1.6 on 2025-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_issues_company_company_priorities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hmg_priorities',
            field=models.TextField(blank=True, default='', verbose_name='HMG priorities'),
        ),
    ]
