# Generated by Django 5.1.6 on 2025-03-06 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_hmg_priorities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccountManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'account manager',
                'verbose_name_plural': 'account managers',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='account_manager',
            field=models.ManyToManyField(related_name='managed_companies', through='core.CompanyAccountManager', to=settings.AUTH_USER_MODEL),
        ),
    ]
