# Generated by Django 5.1.6 on 2025-03-06 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companyaccountmanager_company_account_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name', 'duns_number', 'id'], 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'email', 'id']},
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateTimeField(null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='core.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'company'), name='company_account_manager')],
            },
        ),
    ]
