# Generated by Django 5.1.6 on 2025-03-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_company_options_alter_user_options_engagement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='engagement',
            name='company_account_manager',
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('title', 'company'), name='company_engagement'),
        ),
    ]
