# Generated by Django 5.1.6 on 2025-03-06 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_engagement_company_engagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, default='')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.engagement')),
            ],
        ),
    ]
