# Generated by Django 5.1.6 on 2025-03-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_engagementnote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementnote',
            old_name='details',
            new_name='contents',
        ),
    ]
