# Generated by Django 5.1.7 on 2025-03-12 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_company_sectors_companyaccountmanager_is_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_priorities',
        ),
        migrations.RemoveField(
            model_name='company',
            name='hmg_priorities',
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(choices=[('company_priority', 'Company Priority'), ('hmg_priority', 'HMG Priority')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['insight_type', 'order', '-created_at'],
            },
        ),
    ]
