# Generated by Django 5.1.7 on 2025-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_company_company_priorities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('company_priority', 'Company Priority'), ('hmg_priority', 'HMG Priority'), ('key_person', 'Key Person')], max_length=20),
        ),
    ]
