# Generated by Django 5.1.7 on 2025-03-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_company_company_priorities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='key_people',
        ),
        migrations.CreateModel(
            name='KeyPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_people', to='core.company')),
            ],
        ),
    ]
