# Generated by Django 5.1.7 on 2025-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_company_key_people_keypeople'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keypeople',
            options={'verbose_name_plural': 'Key people'},
        ),
    ]
