# Generated by Django 5.1.7 on 2025-04-01 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_keypeople_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SL0001', 'Advanced engineering'), ('SL0011', 'Aerospace'), ('SL0022', 'Agriculture, horticulture, fisheries and pets'), ('SL0049', 'Airports'), ('SL0050', 'Automotive'), ('SL0071', 'Chemicals'), ('SL0077', 'Construction'), ('SL0078', 'Consumer and retail'), ('SL0102', 'Creative industries'), ('SL0139', 'Defence'), ('SL0140', 'Education and training'), ('SL0169', 'Energy'), ('SL0187', 'Environment'), ('SL0194', 'Financial and professional services'), ('SL0221', 'Food and drink'), ('SL0236', 'Healthcare services'), ('SL0432', 'Logistics'), ('SL0245', 'Maritime'), ('SL0274', 'Medical devices and equipment'), ('SL0279', 'Mining'), ('SL0280', 'Pharmaceuticals and biotechnology'), ('SL0286', 'Railways'), ('SL0287', 'Security'), ('SL0289', 'Space'), ('SL0305', 'Sports economy'), ('SL0312', 'Technology and smart cities'), ('SL0337', 'Water')], max_length=6), blank=True, default=list, null=True, size=None, verbose_name='Sectors'),
        ),
    ]
