# Generated by Django 5.1.7 on 2025-04-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_engagementnote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
