# Generated by Django 5.1.7 on 2025-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_company_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='engagementnote',
            name='contents',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='insight',
            name='details',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
