# Generated by Django 5.1.7 on 2025-04-04 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_company_summary_alter_engagement_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keypeople',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
