# Generated by Django 5.1.7 on 2025-04-04 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_keypeople_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypeople',
            name='id',
        ),
        migrations.AlterField(
            model_name='keypeople',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
