# Generated by Django 5.1.7 on 2025-04-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_keypeople_id_alter_keypeople_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keypeople',
            old_name='uuid',
            new_name='id',
        ),
    ]
