# Generated by Django 5.1.7 on 2025-04-04 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_uuid_keypeople_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypeople',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
