name: tests

run-name: 🔬 @${{ github.triggering_actor }} is checking quality on ${{ github.ref_name }}

on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: mysecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      PGHOST: localhost
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: scl.settings
      COPILOT_ENVIRONMENT_NAME: test
      DEBUG: True

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: pip install -r requirements.txt
      - run: pip install factory_boy pytest pytest-django
      - run: make init
      - run: python manage.py migrate
      - run: pytest
