name: tests

run-name: 🔬 @${{ github.triggering_actor }} is checking quality on ${{ github.ref_name }}

on:
  pull_request:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: mysecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      PGHOST: localhost
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: scl.settings_test
      COPILOT_ENVIRONMENT_NAME: test
      DEBUG: True

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: pip install -r requirements-dev.txt
      - run: make init
      - run: python manage.py migrate
      - run: pytest
  
  e2e-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup xvfb
        run: |
          sudo apt-get update
          sudo apt-get -y install \
          libgtk2.0-0 \
          libgtk-3-0 \
          libgbm-dev \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          libxtst6 \
          xauth \
          xvfb

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Start up services
        run: cp ./sample.env .env && make e2e/up

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run e2e:run